### ISSUE TITLE
cron job doesn't seem to execute itself

### ISSUE THREAD

**Issue by augisbud** [razonyang/docker-php-cron#1]
hello, the default cron job doesn't seem to be executing

**Comment by razonyang** [comment]
Would you please provide the detail how to reproduce this issue?

**Comment by razonyang** [comment]
It seems because /etc/crontab is not a copy of crontab.

```shell
$ docker exec php-cron cat /etc/crontab
// empty file
```

But it works fine by specifying crontab file:

```shell
# crontab file
* * * * * /usr/local/bin/php -r "file_put_contents(sys_get_temp_dir() . '/cron.log', date('Y-m-d H:i:s') . PHP_EOL, FILE_APPEND);"

```

```shell
$ docker run --name php-cron \
    -v /path/to/crontab:/etc/crontab:ro razonyang/php-cron:7.3 \
    /bin/bash -c "/usr/bin/crontab /etc/crontab && /usr/sbin/cron -f"
```

**Comment by razonyang** [comment]
I rebuild 7.3 image and push it to docker hub(works fine), please feel free to pull it again.

Please note that tag `latest` is qual to `7.4` now.
