### ISSUE TITLE
How to install mysqli extension?

### ISSUE THREAD

**Issue by augisbud** [razonyang/docker-php-cron#2]
Hello, sorry to bother you, but the cron job itself is now working perfectly, but one more thing, how do I add mysqli, because it's required for my script, to push updates to the database

**Comment by razonyang** [comment]
This image aim to be more generic, clean and less dependency. Additional extensions(pgsql/mysql) will not be added into this image.

In this case, you can build you own image. Here is an example of `Dockerfile`:

```docker
$ vi DockerFile
# Base image
FROM razonyang/php-cron:7.3

RUN apt-get update

# MySQL extension
RUN docker-php-ext-install mysqli

# Install more extensions
# ...
```

```shell
# Builds image
$ docker build -t my-php-cron ./

# Run container
$ docker run --name my-php-cron my-php-cron

# Verify
$ docker exec my-php-cron php -m | grep mysql
mysqli
```

See [How to install more PHP extensions](https://github.com/docker-library/docs/blob/master/php/README.md#how-to-install-more-php-extensions).

The following command is also useful.
```shell
$ docker exec my-php-cron docker-php-ext-install --help
```
